### ISSUE TITLE
500 internal error.

### ISSUE THREAD

**Issue by rabihaslam** [imranhsayed/woo-next#10]
Please have a look at this. I tried this. But got some errors...

1) The live website: https://woo-next.imranhsayed.now.sh/ : 500 internal error...

2) When cloning this,
sudo git clone git@github.com:imranhsayed/woo-next
Cloning into 'woo-next'...
Warning: Permanently added the RSA host key for IP address 'x.x.x.x' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

3) So I downloaded the zip from here and paste, then at the local testing,
now dev
> Now CLI 16.6.2 dev (beta) — https://zeit.co/feedback/dev
> Error! One or more invalid routes were found:
- Invalid regular expression: "^/product/(?<slug>[^/]+)$"
- Invalid regular expression: "^/category/(?<slug>[^/]+)$"

4) Then I tried with "now", and make it live, that is also 500 internal error.

Actually I am learning this. I am a noob here. This video by Imran sayed on youtube attracts me. So
I tried this. Please help me if I did anything wrong.

**Comment by marquez138** [comment]
Did this get resolved? Im trying the demo with the same errors
