### ISSUE TITLE
Global CSS cannot be imported from files other than your Custom <App>.

### ISSUE THREAD

**Issue by emindemirhan** [imranhsayed/woo-next#117]
I couldn't find a solution all night, please tell me something for fixing this.
![sassnext](https://user-images.githubusercontent.com/59489518/197368610-8a448ecf-6d07-4a18-bce5-56c822648b4b.png)

**Comment by w3bdesign** [comment]
@emindemirhan 

Where are you importing your CSS?

Have you tried importing it in _app.js as the message says?

**Comment by emindemirhan** [comment]
> @emindemirhan 
> 
> Where are you importing your CSS?
> 
> Have you tried importing it in _app.js as the message says?
> 

Yeah sure, it's already importing inside of _app.js

**Comment by w3bdesign** [comment]
@emindemirhan 

It would help if you posted some relevant code, preferably a minimal repro with the error.

Also, have you installed sass in package.json?

**Comment by emindemirhan** [comment]
> @emindemirhan
> 
> It would help if you posted some relevant code, preferably a minimal repro with the error.
> 
> Also, have you installed sass in package.json?

Dear bro thanks for helping, i've tried to run this on github codespaces its worked succesfully, but in my local its still getting same error, i am going to share my codes may you can find a solution for me thank you soo much for helping mate. Also i  am going to invite you to repo if you want you can do change on it bro.
```
_app.js
import "../src/styles/style.scss";
import "../src/styles/main.scss";

import Router from 'next/router';
import NProgress from 'nprogress';

NProgress.configure({ showSpinner: false });
Router.events.on('routeChangeStart', () => NProgress.start());
Router.events.on('routeChangeComplete', () => NProgress.done());
Router.events.on('routeChangeError', () => NProgress.done());

function MyApp({ Component, pageProps }) {
  return <Component {...pageProps} />
}

export default MyApp
```
```
next_config.js
const path = require("path");
const allowedImageWordPressDomain = new URL(process.env.NEXT_PUBLIC_WORDPRESS_URL).hostname

module.exports = {
    trailingSlash: true,
    webpackDevMiddleware: (config) => {
        config.watchOptions = {
            poll: 1000,
            aggregateTimeout: 300,
        };

        return config;
    },
    sassOptions: {
        includePaths: [path.join(__dirname, "styles")],
    },
    /**
     * We specify which domains are allowed to be optimized.
     * This is needed to ensure that external urls can't be abused.
     * @see https://nextjs.org/docs/basic-features/image-optimization#domains
     */
    images: {
        domains: [ allowedImageWordPressDomain, 'via.placeholder.com' ],
    },
};
```

```
package.json
{
  "name": "woo-next",
  "version": "2.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "svg": "svgr -d src/components/icons src/components/icons/svgs"
  },
  "dependencies": {
    "@apollo/client": "^3.3.16",
    "@stripe/stripe-js": "^1.14.0",
    "@svgr/cli": "^5.5.0",
    "@woocommerce/woocommerce-rest-api": "^1.0.1",
    "axios": "^0.21.1",
    "classnames": "^2.3.1",
    "graphql": "^15.4.0",
    "lodash": "^4.17.20",
    "micro": "^9.3.4",
    "next": "^11.1.1",
    "next-stripe": "^1.0.0-beta.9",
    "node-fetch": "^2.6.1",
    "nprogress": "^0.2.0",
    "prop-types": "^15.7.2",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "sass": "^1.29.0",
    "stripe": "^8.148.0",
    "uuid": "^8.3.1",
    "validator": "^13.1.17"
  },
  "devDependencies": {
    "install": "^0.13.0",
    "postcss-flexbugs-fixes": "^5.0.1",
    "postcss-import": "^13.0.0",
    "postcss-preset-env": "^6.7.0",
    "precss": "^4.0.0",
    "tailwindcss": "^1.9.6"
  }
}

```

**Comment by w3bdesign** [comment]
@emindemirhan 

I managed to remove the error message by upgrading the Next.js version to at least 12. 

The main issue with woo-next is that all of the packages are very outdated, so the application will break and require several changes to work.

Another thing is that for some reason, there is a combination of both SCSS and Tailwind for styling, which creates a conflict and makes things confusing and more complicated than necessary. 

You should create the design using just SCSS or Tailwind, not both.

**Comment by emindemirhan** [comment]
> @emindemirhan
> 
> I managed to remove the error message by upgrading the Next.js version to at least 12.
> 
> The main issue with woo-next is that all of the packages are very outdated, so the application will break and require several changes to work.
> 
> Another thing is that for some reason, there is a combination of both SCSS and Tailwind for styling, which creates a conflict and makes things confusing and more complicated than necessary.
> 
> You should create the design using just SCSS or Tailwind, not both.

bro i've upgraded next, react and react dom to higher version and force them to upgrading and its worked thank you soo much for helping.
