### ISSUE TITLE
Update the codes please

### ISSUE THREAD

**Issue by mymakarim** [imranhsayed/woo-next#28]
The issue (add to cart functionality) is solved in the demo app but not in the codes.
please commit the changes here as well or maybe make a video on it explaining what the problem was.
Appreciate your efforts and I was wondering if you could provide a way to chat (Whatsapp or Messenger)

**Comment by imranhsayed** [comment]
@mymakarim some other plugin was creating issue, which I have deactivated. Code changes are not required.
Please open the site in incognito mode.. You can message me on YouTube comments.
