### ISSUE TITLE
Crashes if adding product to cart without an image

### ISSUE THREAD

**Issue by w3bdesign** [imranhsayed/woo-next#34]
Fixed in https://github.com/imranhsayed/woo-next/pull/33

**Comment by imranhsayed** [comment]
@w3bdesign 
I have added comment your the PR.

**Comment by w3bdesign** [comment]
@imranhsayed 

Is the WooCommerce installation local or remote? 

I found out that if I use Xampp, the update takes a minute or two, but is really fast on an online installation.

I recommend that you experiment with a different WooCommerce installation and see if that may be the reason.

**Comment by w3bdesign** [comment]
Just tested again on a local installation with XAMPP, and it works fine. It takes a little bit of time before the cart updates, but I haven't been able to test it on an online installation just yet:

![image](https://user-images.githubusercontent.com/45217974/89129492-10fcb500-d4fe-11ea-83c7-fe3ee3c69db3.png)

**Comment by imranhsayed** [comment]
I shall check it over the weekend. thank you

**Comment by imranhsayed** [comment]
@w3bdesign 
Added the comment on your PR.

**Comment by imranhsayed** [comment]
if the need be we can reopen it.
