### ISSUE TITLE
Clearer slug for single Product

### ISSUE THREAD

**Issue by yudyananda** [imranhsayed/woo-next#35]
Hi @imranhsayed is it any other approach that we can do to make the slug more clearer? the `-${product.productId}` can cause little drawback in SEO.

**Comment by imranhsayed** [comment]
Would you like to contribute and send me a PR with changes?

**Comment by yudyananda** [comment]
Sure, I'll get back to you with the PR

**Comment by yudyananda** [comment]
kindly check #37

**Comment by imranhsayed** [comment]
Great!
Welcome to the contributors club !
I will test it over the weekend and merge.
Thank you 👍

**Comment by imranhsayed** [comment]
@yudyananda 
I have approved and merged your PR.
I have also added your name to the [contributors list ](https://github.com/imranhsayed/woo-next#code-contributors-)
Thank you for your efforts and suggestions.
