### ISSUE TITLE
Template is missing. 

### ISSUE THREAD

**Issue by 1000camels** [imranhsayed/woo-next#38]
I am seeing this message: "Template is missing. Standalone themes need to have a index.php template file. Child themes need to have a Template header in the style.css stylesheet."

Perhaps this is meant to be a headless install. I thought it was a Woocommerce Theme (ie. normal WordPress theme).

Could you clarify?

**Comment by yudyananda** [comment]
@1000camels did you install the whole source code into wordpress as a theme? you cannot install it directly.  woo-next is front-end which run separately from your headless wordpress,   

The things that you should install is the plugins inside [wordpress dir](https://github.com/imranhsayed/woo-next/tree/master/wordpress/plugins)

**Comment by 1000camels** [comment]
Thank you. I now understand. I am exploring ways to use react with woocommerce within a standard WP theme. I'm not ready for a headless install yet

**Comment by imranhsayed** [comment]
Sure feel free to ask any more questions if you may have in future.
