### ISSUE TITLE
Remove from cart

### ISSUE THREAD

**Issue by mhdmunawar** [imranhsayed/woo-next#40]
Remove items from cart not working. Session expired message showing

**Comment by imranhsayed** [comment]
Thanks for writing. Please test it on live site https://woo-next.imranhsayed.now.sh/ and clear your previous localStorage or try it in incognito.
![demo-remove-from-cart](https://user-images.githubusercontent.com/11497423/90045689-048e0e80-dced-11ea-90ba-c582d2289b55.gif)
