### ISSUE TITLE
Without image application is crashing

### ISSUE THREAD

**Issue by wasiqaftab** [imranhsayed/woo-next#41]
First of all thanks for this repo this is exactly what i need to start my project. 

But i am having few issues its crashing the app in functions.js file

	```
product.image = {
			sourceUrl: givenProduct.image.sourceUrl,
			srcSet: givenProduct.image.srcSet,
			title: givenProduct.image.title
		};

```
can you please guide what i am doing wrong

**Comment by imranhsayed** [comment]
You can use default image, when product image is not available
https://github.com/imranhsayed/woo-next#configuration-wrench

**Comment by wasiqaftab** [comment]
brother I have Tried default image which is in your repo but didnt work. also if i add any external css fonts its crashing css i added the fileloader lib as well sorry i am not very much exp in next. can you guide me what can i do in that case

**Comment by imranhsayed** [comment]
You can take reference from my webpack tutorial  which will help you understand how to set up fonts 
https://www.youtube.com/playlist?list=PLD8nQCAhR3tRSHDQDZi3jGSgQ_9VNY4gu

https://youtu.be/TUkaDzZbfl8
https://youtu.be/Lm8qve6mOJ8

**Comment by imranhsayed** [comment]
Closing this, assuming this is resolve. If the need be we can reopen.
