### ISSUE TITLE
The checkout process failed due to input shipping method

### ISSUE THREAD

**Issue by yudyananda** [imranhsayed/woo-next#42]
First of all I want to thank you for creating this next.js tutorial. Currently I have successfully followed the guidelines that you provided. Adding products to cart and so on and lastly create checkout page.

Unfortunately, I'm stuck in the checkout process because at that stage there must be input which contain the shipping method

Maybe this could be solve by adding additional data in [getFormattedCart](https://github.com/imranhsayed/woo-next/blob/822502afc55cf0d20f98c5c1dbfc942eb58aa653/functions.js#L200) function where we can get a shipping method to pass to the checkout page, 
```javascript
//  functions.js
export const getFormattedCart = (data) => {
  ...
  formattedCart.shippingOption = data.cart.availableShippingMethods...  // but of course it won't work because the user address is not yet exist 
}
```
This is quite confusing because I'm new to react and next.js (matter of fact in javascript too) so I really hope you have future plans to finish unresolved step like creating account etc (including this issue)

By the way I've made a few updates which include

1. Using the built-in css feature from next.js
2. Using the Apollo Client 3 `@ Apollo / client`
3. Replace `client-config` and` siteConfig` with `.env`
4. Made index and product page become static by taking advantage of the `getStaticProps` and incremental build to make page still dynamic but load faster
`
If you allowed me, I would like to contribute by submitting PR as soon as possible

**Comment by imranhsayed** [comment]
Yes @yudyananda Your PR will be much appreciated for any updates or new features.
You are a contributor to this open-source project now.
I have already created a new project with React and GraphQL using Gatsby, where I have implement authentication, login , registration, create a new account at the time of placing the order, my account page, PWA and many more new features.
You can take reference from my repo code and feel free to contribute to this project by adding those features.
https://github.com/imranhsayed/gatsby-woocommerce-themes

**Comment by imranhsayed** [comment]
I have made the updates please please pull the latest changes from master and test
https://github.com/imranhsayed/woo-next/releases/tag/v2.1.0
Live Demo: https://woo-next-imranhsayed.vercel.app/
