### ISSUE TITLE
Questions about this theme

### ISSUE THREAD

**Issue by Ebeldev** [imranhsayed/woo-next#43]
Hi Imranhsayed, 

I saw this repo and your course. I haven't finish it yet. But I had a few questions. 

How would you implement some search box ?
How would you implement a filter base on attributs?
Can you easily implement cross-selling into products?
Can you easily implement shiiping with shipping options in the backend ?
How would you implement a multilingual WooCommerce site build with WPML or Polylang?

Thank for this repo and your time.

Étienne

**Comment by imranhsayed** [comment]
Thanks you!
The wp-graphql plugin is very powerful . It has the ability for you to query for search, filter etc.
You can implement js-search or search query. I have implemented one in Gatsby that works offline as well, Here is the [link](https://youtu.be/ygaE8ZdPEX8) for the demo.
I haven't tried cross selling, but you should be able to implement it.
Entire backend is handled by WooCommerce in WordPress, so yes you can add shipping options in the backend.
