### ISSUE TITLE
Why clientConfig?

### ISSUE THREAD

**Issue by darrylmorley** [imranhsayed/woo-next#44]
Hi,
Thanks for the code and course, it's been a fantastic help.
I just wonder why you use a clientConfig file rather than a .env?

Also, I see that your adding client-config.js to the .gitignore file. How can these parameters be used with vercel?

Thanks

**Comment by imranhsayed** [comment]
Hey @darrylmorley,
I agree we can use .env like explained [here](https://nextjs.org/docs/basic-features/environment-variables#exposing-environment-variables-to-the-browser) 
This is an open source project . Would you like to contribute to the project by raising the PR to make those changes?

**Comment by darrylmorley** [comment]
Yes certainly
