### ISSUE TITLE
Adding the first time to the cart takes more than 7 seconds

### ISSUE THREAD

**Issue by oskr1103** [imranhsayed/woo-next#57]
First of all thank you very much, your tutorials have helped me a lot, I have finished this project, but when I add a product to the cart, only the first time it takes a long time, I have the deployment in vercel and the wordpress in a dedicated hosting, I leave you the link to see if you can guide me in finding the solution, thank you very much you are a great teacher https://flowershop.vercel.app/

**Comment by w3bdesign** [comment]
@oskr1103 It doesn't seem to be that slow here.

Can you share more details about the plugins and versions you are currently using?

**Comment by oskr1103** [comment]
I currently use graph version 1, but additionally now it is presenting me with an error that says token expired, that happens if the product remains more than two days, when I try to delete it, it gives me that error

**Comment by w3bdesign** [comment]
> 
> 
> I currently use graph version 1, but additionally now it is presenting me with an error that says token expired, that happens if the product remains more than two days, when I try to delete it, it gives me that error

@oskr1103 

I would recommend that you set a cookie for when the session was set, and then compare that to the current time, and automatically refetch the session if it has expired (I think it expires after 24 hours or 48 hours).

I have implemented this feature myself, you can take a look at this file:

https://github.com/w3bdesign/nextjs-woocommerce/blob/master/utils/apollo/ApolloClient.js

**Comment by oskr1103** [comment]
Thank you very much, I just did the implementation, I'll tell you how it goes, very kind

**Comment by oskr1103** [comment]
Thank you very much for the proposal of the function, everything has been ok, on the other hand something curious happens to me I do not know if you can guide me, currently the store has 100 products, but if I add one more, one or two always breaks and gives me Error 404

**Comment by w3bdesign** [comment]
> 
> 
> Thank you very much for the proposal of the function, everything has been ok, on the other hand something curious happens to me I do not know if you can guide me, currently the store has 100 products, but if I add one more, one or two always breaks and gives me Error 404

I doubt that is related to the session.

Did you check the console after adding the product?

**Comment by oskr1103** [comment]
You are right with the session, no, I had a question after that, if the console says that the product error 404 could not be obtained, the funny thing is that in the product thumbnail it looks good, but when I go to detail to the product page is that that happens, but it is when I pass 100 products in wordpress

**Comment by w3bdesign** [comment]
@oskr1103 

Check the GraphQL IDE and see if you can fetch 101 products from there. 
That way you should be able to see if it is a GraphQL error or not.

**Comment by oskr1103** [comment]
Thanks for answering, this is the error that I get in the console, and in the ide if it brings all the products

![image](https://user-images.githubusercontent.com/30869944/106039675-637eee80-60a7-11eb-90d0-563aac00e6df.png)

**Comment by oskr1103** [comment]
Thanks for answering, this is the error that I get in the console, and in the ide if it brings all the products
![image](https://user-images.githubusercontent.com/30869944/106040096-f4ee6080-60a7-11eb-9358-7e8d3b516df2.png)

**Comment by w3bdesign** [comment]
> 
> 
> Thanks for answering, this is the error that I get in the console, and in the ide if it brings all the products
> ![image](https://user-images.githubusercontent.com/30869944/106040096-f4ee6080-60a7-11eb-9358-7e8d3b516df2.png)

Hard to give a good reply without knowing more details. 

I suggest you open a new issue and provide as much details as possible, and then maybe someone will be able to assist.

**Comment by w3bdesign** [comment]
@oskr1103 

If you can share some GraphQL code it would be easier to troubleshoot and help you out.
