### ISSUE TITLE
where is the wooconfig to put consumer key and secret?

### ISSUE THREAD

**Issue by ebisLab** [imranhsayed/woo-next#61]
Hi. im trying to get this project up and running, I was only able to put the .env variable in for the woocommerce where i have my graphql  link, but how is it pulling the info without the key and secret?
I'm asking because I'm getting an `ApolloError: Only absolute URLs are supported ` and `ApolloError: Unexpected token < in JSON at position 0 ` i'm not entirely sure how to start debugging

**Comment by oskr1103** [comment]
> Hi. im trying to get this project up and running, I was only able to put the .env variable in for the woocommerce where i have my graphql link, but how is it pulling the info without the key and secret?
> I'm asking because I'm getting an `ApolloError: Only absolute URLs are supported ` and `ApolloError: Unexpected token < in JSON at position 0 ` i'm not entirely sure how to start debugging

for this error try using direct wordpress url (not environment variable) and tell me if it works fine

**Comment by ebisLab** [comment]
it worked, I was using the old version of this set up.
