### ISSUE TITLE
How to removes token when it expires

### ISSUE THREAD

**Issue by ebisLab** [imranhsayed/woo-next#62]
Is there a way we can remove the token from local storage when it expires. I'm looking into the Apollo client

**Comment by oskr1103** [comment]
hi this problem is fixed in this answer, hope I can help https://github.com/imranhsayed/woo-next/issues/57#issuecomment-767080389

**Comment by oskr1103** [comment]
> Is there a way we can remove the token from local storage when it expires. I'm looking into the Apollo client

hi this problem is fixed in this answer, hope I can help #57 (comment)

**Comment by ebisLab** [comment]
You're right. This issue is solved.

**Comment by oskr1103** [comment]
good ;)
