### ISSUE TITLE
How can query wooCountries from graphql

### ISSUE THREAD

**Issue by trithien98** [imranhsayed/woo-next#80]
Hi , i had install 2 plugin wp-graphql and wp-graphql-woocomerce in new version update from plugin folder.
And i want to query  country , after install 2 plugin ,I cant see field wooCountries from graphql ide .So how can i do this.Thank you
`import { gql } from "@apollo/client";

/**
 * GraphQL countries query.
 */
const GET_COUNTRIES = gql`query GET_COUNTRIES{
  wooCountries {
    billingCountries {
      countryCode
      countryName
    }
    shippingCountries {
      countryCode
      countryName
    }
  }
}`;

export default GET_COUNTRIES;`

**Comment by omaSpencer** [comment]
Hi, 
same issue for me.
I get this error message:
`Cannot query field "wooCountries" on type "RootQuery".`

**Comment by omaSpencer** [comment]
@trithien98 , need to install Headless CMS plugin too.

**Comment by trithien98** [comment]
> @trithien98 , need to install Headless CMS plugin too.

yah. i miss this plugin
